---
# snapshot_appendix is coming from
- hosts: all
  gather_facts: true

  vars:
    installed_guests: []
    new_snapshots: []

  pre_tasks:
  # supported_operations is coming from inventory/group_vars/all.yml
  - name: lcm | Ensure operation is defined
    ansible.builtin.assert:
      that:
      - operation is defined and operation != ""
      - operation in supported_operations

  tasks:
  - name: lcm | Ensure libvirtd is running
    ansible.builtin.systemd:
      name: libvirtd
      state: started
      enabled: true
    when: ansible_os_family == "RedHat"

  - name: lcm | Read guest build inputs
    ansible.builtin.debug:
      var: kvm_guest_machines

  - name: lcm | Get the VM already exists on KVM host
    ansible.builtin.shell: |
      virsh list --all|awk '{print $2}'|egrep -v "^Name|^-|^$"
    register: _installed_vms

  - name: lcm | Show available VMs on KVM host
    ansible.builtin.debug:
      var: _installed_vms.stdout_lines

  - name: lcm | Ensure VMs listed in 'kvm_guest_machines' are exists
    ansible.builtin.assert:
      that:
      - item.name in _installed_vms.stdout_lines
    loop: "{{ kvm_guest_machines }}"
    loop_control:
      label: "{{ item.name }}"

  - name: lcm | Call include/snapshot.yml to take snapshot
    include_tasks: include/snapshot.yml
    when: operation == 'snapshot'

  - name: lcm | Call include/delete.yml to delete machines
    include_tasks: include/delete.yml
    when: operation == 'delete'

  - name: lcm | Call include/shutdown.yml to shutdown machines
    include_tasks: include/shutdown.yml
    when: operation == 'shutdown'

  - name: lcm | Call include/start.yml to start machines
    include_tasks: include/start.yml
    when: operation == 'start'
