---


- name: Revert master VMs snapshot
  command: virsh snapshot-revert "{{item}}" "{{item}}"-all-predone
  with_items:
    - "{{master1}}"
    - "{{master2}}"
    - "{{master3}}"
  ignore_errors: false
