all:
  hosts:
    remote-kvm-host:
      ansible_host: 192.168.100.108
      ansible_user: root
      ansible_connection: ssh
  vars:
    ansible_python_interpreter: /usr/bin/python3
    ansible_become: true
    ansible_become_method: sudo
    ansible_become_user: root
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
    ansible_ssh_extra_args: '-o StrictHostKeyChecking=no'
  children:
    kvm_hosts:
      hosts:
        remote-kvm-host:
