- name: start | Start machines
  ansible.builtin.shell: |
    virsh start {{ vm }}
  register: start_machine
  loop: "{{ kvm_guest_machines|map(attribute='name')|list }}"
  loop_control:
    loop_var: vm

- name: start | Wait for machines to be started
  ansible.builtin.shell: |
    for vm in {{ vms }}; do
      until [[ "$(virsh dominfo "$vm" | grep ^State | cut -d':' -f2 | xargs)" == "running" ]]; do
        echo "Waiting for $vm to start..."
        sleep 5
      done
      echo "$vm is now running."
    done
  register: wait_start
  changed_when: false
  vars:
    vms: "{{ kvm_guest_machines | map(attribute='name') | join(' ') }}"
