---
- name: Install KVM packages and setup KVM host
  hosts: all
  gather_facts: true

  vars:
    guest_images: "/var/lib/libvirt/images"
    image_artifactory: "/var/lib/libvirt/images/artifactory"
    kvm_packages:
      - bash-completion
      - qemu-kvm
      - virt-install
      - virt-viewer
      - libvirt
      - virt-top
      - libguestfs-tools
      - dmidecode
      - net-tools
      - guestfs-tools
      - openssh-askpass
      # - epel-release
      # - epel-next-release
      # - wget

  tasks:
    - name: Install KVM related packages on RedHat Based systems
      ansible.builtin.dnf:
        name: "{{ kvm_packages }}"
      when: ansible_os_family == "RedHat" and ansible_pkg_mgr in ["dnf", "yum", "microdnf", "dnf5"]

    
    - name: Install KVM related packages on RedHat based automic hosts
      ansible.builtin.command:
        cmd: rpm-ostree install {{ kvm_packages | join(' ') }} --allow-inactive
      when: ansible_os_family == "RedHat" and ansible_pkg_mgr == "atomic_container"
      register: _rpm_ostree_install
      changed_when: "'Downloading' in _rpm_ostree_install.stdout or 'Installing' in _rpm_ostree_install.stdout"
      failed_when: 
        - _rpm_ostree_install.rc != 0
        - "'already requested' not in _rpm_ostree_install.stderr"

    - name: Ask user if they want to reboot now after rpm-ostree install
      ansible.builtin.pause:
        prompt: "rpm-ostree packages installed. A reboot is required to apply changes else Abort playbook. Reboot now? (y/n): "
      register: _reboot_answer
      when: _rpm_ostree_install is defined and _rpm_ostree_install is changed
    
    - name: Set reboot decision fact
      ansible.builtin.set_fact:
        reboot_decision: "{{ _reboot_answer.user_input | lower == 'y' }}"
      when: _rpm_ostree_install is defined and _rpm_ostree_install is changed
    
    - name: Reboot after rpm-ostree install on Silverblue
      ansible.builtin.reboot:
        reboot_timeout: 300
      when: reboot_decision is defined and reboot_decision | default(false)

    - name: Abort playbook if reboot not confirmed
      ansible.builtin.fail:
        msg: "Reboot is required to apply rpm-ostree package changes. Aborting playbook as per user choice."
      when: reboot_decision is defined and not reboot_decision | default(true)

    - name: Start libvirtd
      ansible.builtin.systemd:
        name: libvirtd
        state: started
        enabled: true

    - name: Create image store directories
      ansible.builtin.file:
        path: "{{ item }}"
        mode: '0755'
        state: directory
        owner: root
        group: root
      with_items:
        - "{{ guest_images }}"
        - "{{ image_artifactory }}"

    - name: Check if kvm module is loaded
      ansible.builtin.command: modinfo kvm
      ignore_errors: true
      register: _kvm_mod
      changed_when: false

    - name: Load kvm module
      community.general.modprobe:
        name: kvm
      when: _kvm_mod.rc != 0

    - name: Run virt-host-validate qemu
      ansible.builtin.command: virt-host-validate qemu
      register: _virt_validate
      ignore_errors: true
      changed_when: false

    - name: Run assert
      ansible.builtin.assert:
        that:
          - not _virt_validate.stdout_lines is search('FAIL')
        fail_msg:
          - "'virt-host-validate' validation failed"
