---

- hosts: all
  gather_facts: true

  vars:
    images_to_be_download: []
    create_networks: []
    # Following two variables are required to be true to include respective tasks
    # Also provide control on re-running the playbook for only one of these tasks by setup.sh
    networks: true
    images: true

  tasks:
  - name: prepare-kvm | Ensure libvirtd is running
    ansible.builtin.systemd:
      name: libvirtd
      state: started
      enabled: true
    when: ansible_os_family == "RedHat"

  # - name: prepare-kvm | Include tasks/images.yml
  #   ansible.builtin.include_tasks: tasks/images.yml
  #   when: images|bool

  - name: prepare-kvm | Include tasks/networks.yml
    ansible.builtin.include_tasks: tasks/networks.yml
    when: networks|bool
