---
- name: Set Max RAM in worker VMs
  command: virsh setmaxmem "{{ item.vm }}" "{{ item.ram }}" --config
  with_items:
    - { vm: "{{node1}}", ram: '2G' }
    - { vm: "{{node2}}", ram: '2G' }

- name: Set Usable RAM in worker VMs
  command: virsh setmem "{{ item.vm }}" "{{ item.ram }}" --config
  with_items:
    - { vm: "{{node1}}", ram: '2G' }
    - { vm: "{{node2}}", ram: '2G' }
