---
- name: Set Max RAM in load balancer VMs
  command: virsh setmaxmem "{{ item.vm }}" "{{ item.ram }}" --config
  with_items:
    - { vm: "{{lb01}}", ram: '1G' }
    - { vm: "{{lb02}}", ram: '1G' }

- name: Set Usable RAM in load balancer VMs
  command: virsh setmem "{{ item.vm }}" "{{ item.ram }}" --config
  with_items:
    - { vm: "{{lb01}}", ram: '1G' }
    - { vm: "{{lb02}}", ram: '1G' }
