---

- name: Set Max CPU for worker VMs
  command: virsh setvcpus "{{ item.vm }}" "{{ item.cpu }}" --config --maximum
  with_items:
    - { vm: "{{node1}}", cpu: '2' }
    - { vm: "{{node2}}", cpu: '2' }

- name: Set Usable CPU for worker VMs
  command: virsh setvcpus "{{ item.vm }}" "{{ item.cpu }}" --config
  with_items:
      - { vm: "{{node1}}", cpu: '2' }
      - { vm: "{{node2}}", cpu: '2' }
