---

- name: Set Max CPU for load balancer VMs
  command: virsh setvcpus "{{ item.vm }}" "{{ item.cpu }}" --config --maximum
  with_items:
    - { vm: "{{lb01}}", cpu: '2' }
    - { vm: "{{lb02}}", cpu: '2' }

- name: Set Usable CPU for load balancer VMs
  command: virsh setvcpus "{{ item.vm }}" "{{ item.cpu }}" --config
  with_items:
    - { vm: "{{lb01}}", cpu: '2' }
    - { vm: "{{lb02}}", cpu: '2' }
