---

- name: Set Max CPU for client VM
  command: virsh setvcpus "{{ item.vm }}" "{{ item.cpu }}" --config --maximum
  with_items:
    - { vm: "{{client}}", cpu: '2' }

- name: Set Usable CPU for client VM
  command: virsh setvcpus "{{ item.vm }}" "{{ item.cpu }}" --config
  with_items:
    - { vm: "{{client}}", cpu: '2' }
