---

- name: restart libvirtd
  service:
    name: libvirtd
    state: restarted
  ignore_errors: false

- name: libvirtd check
  wait_for:
    path: /var/run/libvirt/libvirt-admin-sock
    state: present
#      sleep: 5
  ignore_errors: false
