---

- name: Create workers VMs for K8s cluster using Ubuntu16.04 template
  command: virt-clone -o "{{ubuntu_template}}" -n "{{item}}" -f "{{vms_disk_path}}"/"{{item}}".qcow2
  with_items:
      - "{{node1}}"
      - "{{node2}}"
  ignore_errors: false
