---

- name: Create kubernetes client VM for K8s cluster using Ubuntu16.04 template
  command: virt-clone -o "{{ubuntu_template}}" -n "{{item}}" -f "{{vms_disk_path}}"/"{{item}}".qcow2
  with_items:
      - "{{client}}"
  ignore_errors: false
