---

- name: artifacts | Create {{ build_artifacts_dir }} directory
  ansible.builtin.file:
    path: "{{ build_artifacts_dir }}"
    state: directory
    mode: '0755'

- name: Block to Generate machine inventory artifacts
  block:
  # Generate ansible inventory from new created machines
  - name: inventory artifacts | Generate ansible inventory from new created machines
    ansible.builtin.template:
      src: "{{ playbook_dir }}/templates/ansible-inventory.j2"
      dest: "{{ inventory_artifact }}"
      mode: 644
    vars:
      machines: "{{ created_machine_properties }}"

  - name: inventory artifacts | Show generated ansible inventory
    ansible.builtin.debug:
      msg: "Generated Ansible inventory file is {{ inventory_artifact }}"

  - name: inventory artifacts | Pull artifacts from on ansible controller in {{ build_artifacts_dir }}
    ansible.builtin.fetch:
      src: "{{ inventory_artifact }}"
      dest: "{{ build_artifacts_dir }}/"
      flat: yes
      fail_on_missing: yes

- name: artifacts | Get all generated artifacts
  ansible.builtin.set_fact:
    artifacts_list: "{{ lookup('fileglob', build_artifacts_dir) }}"

- name: artifacts | Show generated artifacts
  ansible.builtin.debug:
    msg:
    - "Generated artifacts are in {{ build_artifacts_dir }} on ansible controller:"
    - "{{ artifacts_list|split(',') }}"
