---

# This playbook to deploy VMs in KVM for kubernetes cluster

- hosts: rhel7-home
#- hosts: localhost
  become: true
  become_method: sudo
  vars_files:
    - group_vars/all
  pre_tasks:
    - name: pre_task | Set OS template for Ubuntu
      set_fact:
        os_template: "{{ ubuntu_template }}"
      when:
        - ansible_distribution|string == 'Ubuntu'

    - name: pre_task | Set OS template for CentOS
      set_fact:
        os_template: "{{ centos_template }}"
      when:
        - ansible_distribution|string == 'CentOS'

    - debug:
        var: os_template
  roles:
    #- 1-vm-create
    #- 2-vm-resources
    #- 3-start-vms
    - 4-post-build
    #- 5-post-build
    #- 6-vm-delete
