---

- hosts: all
  gather_facts: true
  become: yes

  vars:
    template_machine: true
    machine_reboot: true

  tasks:
  - name: Include role os-configuration
    ansible.builtin.include_role:
      name: os-configuration

  - name: Include os-tuning role
    ansible.builtin.include_role:
      name: os-tuning
      tasks_from: "{{ item }}"
    loop:
      - grub-tuning.yml
      - dhcp-identifier.yml