---

- hosts: all
  gather_facts: true
  become: yes

  vars_files:
    - ../vars/clone-machines.yml

  tasks:
  - name: include role guest-cpu-ram
    ansible.builtin.include_role:
      name: guest-cpu-ram
