---

- name: 3-start-vms | Start ALL VMs
  shell: |
    for vm in `virsh list --all|egrep -i kube|awk '{print $2}'`;do
      virsh start $vm
    done
  register: start_vm

- name: 3-start-vms | Get Started VMs count
  shell: virsh list|egrep -i kube|awk '{print $2}'
  register: get_started_count
  when: start_vm is succeeded

- debug:
    msg: "All Kube VMs got started..."
  when: "get_started_count.stdout_lines|length == total_created_vms.stdout"
  ignore_errors: false

- debug:
    var: get_started_count.stdout_lines
