
- hosts: all
  gather_facts: true

  vars:
    epel_repo:
    - os: Rocky
      package: epel-release
    dev_packages:
    - os: RedHat
      packages:
      - "@Development Tools"
      - python3-pip
      - numactl-devel
      - glibc
      - pciutils
      - dmidecode
    pip_modules:
    - meson
    - ninja
    - pyelftools
    dpdk_tool: https://fast.dpdk.org/rel/dpdk-24.03.tar.xz
    hugepages:
    - node: node0
      size: 2048 # In KB
      reserve: 64 # No. of pages

  tasks:
  - name: Install epel repo
    ansible.builtin.dnf:
      name: "{{ item.package }}"
      state: latest
    with_items: "{{ epel_repo }}"
    when: item.os == ansible_distribution

  - name: Install required packages
    ansible.builtin.dnf:
      name: "{{ item.packages }}"
    with_items: "{{ dev_packages }}"
    when:
    - ansible_distribution in ["Rocky"]
    - item.os == "RedHat"

  - name: Install python modules
    ansible.builtin.pip:
      name: "{{ pip_modules }}"

  - name: Download dpdk
    ansible.builtin.get_url:
      url: "{{ dpdk_tool }}"
      dest: /root/

  - name: Check if /dev/hugepages is already mounted
    ansible.builtin.command: findmnt /dev/hugepages
    register: _hpmnt
    ignore_errors: true

  - name: Mount /dev/hugepages
    ansible.builtin.shell: |
      mkdir -p /dev/hugepages
      mountpoint -q /dev/hugepages || mount -t hugetlbfs nodev /dev/hugepages
    when: _hpmnt.rc != 0

  - name: Reserve the hugepages
    ansible.builtin.shell: |
      echo {{ item.reserve }} > /sys/devices/system/node/{{ item.node }}/hugepages/hugepages-{{ item.size }}kB/nr_hugepages
    with_items: "{{ hugepages }}"


