
- hosts: all
  gather_facts: true

  tasks:
  - name: Include os-configuration role
    ansible.builtin.include_role:
      name: os-configuration

  - name: Include os-tuning role to setup vconsole, and disable biosdevname
    ansible.builtin.include_role:
      name: os-tuning
