---

- name: Get attached interfaces of VMs
  shell: for i in `cat /var/tmp/k8s-vms/k8s_domain`;do virsh domiflist $i|grep -i virtio >> /var/tmp/k8s-vms/k8s-vm_interface;done

- name: check /var/tmp/k8s-vms/k8s-vm_interface
  stat:
    path: /var/tmp/k8s-vms/k8s-vm_interface
  ignore_errors: false

- name: List VM interfaces
  shell: cat /var/tmp/k8s-vms/k8s-vm_interface
  register: interface_list
- debug:
    var: interface_list.stdout
