---

- name: Get VM IP addresses
  shell: for i in `cat /var/tmp/k8s-vms/k8s_domain`;do virsh domifaddr $i|awk 'FNR==3 {print $4}'|cut -d'/' -f1 >> /var/tmp/k8s-vms/k8s_vm_ips;done

- name: check /var/tmp/k8s-vms/k8s_vm_ips
  stat:
    path: /var/tmp/k8s-vms/k8s_vm_ips
  ignore_errors: false

- name: List VM IPs
  shell: cat /var/tmp/k8s-vms/k8s_vm_ips
  register: list_vm_ip
- debug:
    var: list_vm_ip.stdout
