---

- name: Copy master VMs interfaces configuration files to KVM host to copy to VMs
  template:
    src: "{{item}}"
    dest: /var/tmp/k8s-vms/
    owner: stack
    group: stack
    mode: 0644
  with_items:
    - k8s-master1.interface.j2
    - k8s-master2.interface.j2
    - k8s-master3.interface.j2
  ignore_errors: false

- name: Copy worker VMs interfaces configuration files to KVM host to copy to VMs
  template:
    src: "{{item}}"
    dest: /var/tmp/k8s-vms/
    owner: stack
    group: stack
    mode: 0644
  with_items:
    - k8s-node1.interface.j2
    - k8s-node2.interface.j2
  ignore_errors: false

- name: Copy load balancer VMs interfaces configuration files to KVM host to copy to VMs
  template:
    src: "{{item}}"
    dest: /var/tmp/k8s-vms/
    owner: stack
    group: stack
    mode: 0644
  with_items:
    - k8s-lb01.interface.j2
    - k8s-lb02.interface.j2
  ignore_errors: false

- name: Copy client interfaces configuration files to KVM host to copy to VMs
  template:
    src: "{{item}}"
    dest: /var/tmp/k8s-vms/
    owner: stack
    group: stack
    mode: 0644
  with_items:
    - k8s-client.interface.j2
  ignore_errors: false

- name: Copy hosts file to KVM host to copy to VMs
  template:
    src: "{{item}}"
    dest: /var/tmp/k8s-vms/
    owner: stack
    group: stack
    mode: 0644
  with_items:
    - hosts_file.j2
  ignore_errors: false
