---

- name: Install python package in VMs
  shell: for i in "{{item}}";do ssh -o StrictHostKeyChecking=no stack@$i "sudo apt install python -y";done
  with_items:
    - "{{master1_ip}}"
    - "{{master2_ip}}"
    - "{{master3_ip}}"
    - "{{node1_ip}}"
    - "{{node2_ip}}"
    - "{{lb01_ip}}"
    - "{{lb02_ip}}"
    - "{{client_ip}}"

  ignore_errors: false
