---

- include: 1-domains.yaml
- include: 2-domain-interface.yaml
- include: 3-domain-ips.yaml
- include: 4-guest-vm-nic.yaml
- include: 5-copy-interface-templates-to-kvm.yaml
- include: 6-copy-interface-files-kvm-to-vm.yaml
- include: 7-reboot-vms.yaml
- include: 8-install-required-pkgs.yaml
- include: 9-delete-tmp-files.yaml
