---

- hosts: localhost
  gather_facts: true
  become: yes

  vars_files:
    - ../vars/openstack-vms.yml

  tasks:

  - name: Stop VMs
    ansible.builtin.shell: |
      virsh shutdown {{item.name}}
      sleep 10
    with_items: "{{kvm_deployment.virtual_machines}}"

  - name: Delete existing VMs
    ansible.builtin.command: virsh undefine {{item.name}} --remove-all-storage
    with_items: "{{kvm_deployment.virtual_machines}}"
