---

- hosts: localhost
  gather_facts: true
  become: true

  vars_files:
    - ../vars/openstack-vms.yml

  pre_tasks:
  - name: Run Asserts
    ansible.builtin.assert:
      that:
        - kvm_deployment.template is defined
        - kvm_deployment.virtual_machines is defined
        - kvm_deployment.net_list is defined

  tasks:
  - name: Inclue role to create clones
    ansible.builtin.include_role:
      name: create-vm-clones

  - name: Include role to set cpu and memory
    ansible.builtin.include_role:
      name: guest-cpu-ram
  
  - name: Include role  to set additional networks on VM
    ansible.builtin.include_role:
      name: attach-network-to-guest

  - name: Include role to setup static IP in VMs
  

  