---
- hosts: localhost
  gather_facts: true
  become: true

  vars_files:
    - ../vars/openstack-vms.yml

  roles:
  - role: generate-inventory


- hosts: vms_group
  gather_facts: true
  become: true

  vars_files:
    - ../vars/openstack-vms.yml

  roles:
  - role: set-static-ip